name: vert.x (4.x)

on:
  push:
    branches:
      - vert.x-4.x

jobs:
  ci:
    name: Any (supported)
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build project
        run: ./gradlew clean build
