name: CI

on:
  push:
    branches:
      - master

jobs:
  hotspot-supported:
    name: Any (supported)
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Build project
        run: ./gradlew clean build
