name: CI

on:
  push:
    branches:
      - master

jobs:
  hotspot-supported:
    name: Any (supported)
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Build project
        run: ./gradlew clean build
  sonar:
    name: SonarCloud
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        SONAR_TOKEN: ${{ secrets.sonarcloud }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Build project
        run: ./gradlew clean build sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=romanpierson -Dsonar.projectKey=romanpierson_vertx-web-accesslog 
 