name: Sonar

on:
  push:
    branches:
      - master

jobs:
  sonar:
    name: SonarCloud
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        SONAR_TOKEN: ${{ secrets.sonarcloud }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Build project
        run: ./gradlew clean build  sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=romanpierson -Dsonar.projectKey=romanpierson_vertx-web-accesslog
 